### ISSUE TITLE
console lexer crashes if line ends with \

### ISSUE THREAD

**Issue by mojavelinux** [rouge-ruby/rouge#1602]
**Name of the lexer**: console

**Rouge version**: 3.23.0

**Code sample**

```
$ cd application\bin\
```

**Error**

```
3: from /.../.bundle/gems/ruby/2.7.0/gems/rouge-3.23.0/lib/rouge/lexer.rb:452:in `lex'
2: from /.../.bundle/gems/ruby/2.7.0/gems/rouge-3.23.0/lib/rouge/lexer.rb:462:in `continue_lex'
1: from /.../.bundle/gems/ruby/2.7.0/gems/rouge-3.23.0/lib/rouge/lexers/console.rb:186:in `stream_tokens'
/.../.bundle/gems/ruby/2.7.0/gems/rouge-3.23.0/lib/rouge/lexers/console.rb:147:in `process_line': undefined method `strip' for nil:NilClass (NoMethodError)
```

**Comment by mojavelinux** [comment]
I'd be willing to submit a PR to fix this issue. Just let me know if you're interested.

**Comment by tancnle** [comment]
@mojavelinux Thank you for the offer ❤️ Yes we are more than happy to review your PR 🙏🏼

**Comment by mojavelinux** [comment]
Great! I will submit one.

**Comment by mojavelinux** [comment]
I've submitted a PR, as promised.
