### ISSUE TITLE
[Error] Parsing documentation

### ISSUE THREAD

**Issue by aytekinar** [rouge-ruby/rouge#505]
Hey,

I am using Arch Linux and having problems updating my gems when it comes to rouge. The following error is obtained when I write `gem install github-pages travis-cli` followed by `gem update`:

```
Parsing documentation for rouge-2.0.2
/usr/lib/ruby/2.3.0/rdoc/token_stream.rb:60:in `block in add_tokens': failed to allocate memory (NoMemoryError)
    from /usr/lib/ruby/2.3.0/rdoc/token_stream.rb:60:in `each'
    from /usr/lib/ruby/2.3.0/rdoc/token_stream.rb:60:in `add_tokens'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby_tools.rb:58:in `block in get_tk'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby_tools.rb:57:in `each'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby_tools.rb:57:in `get_tk'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1522:in `block in parse_method_or_yield_parameters'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1489:in `loop'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1489:in `parse_method_or_yield_parameters'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1906:in `parse_yield'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1693:in `parse_statements'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1363:in `block in parse_method_params_and_body'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby_tools.rb:146:in `token_listener'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1340:in `parse_method_params_and_body'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1326:in `parse_method'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1679:in `parse_statements'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:801:in `parse_class_regular'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:747:in `parse_class'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1673:in `parse_statements'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1562:in `parse_module'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1676:in `parse_statements'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1562:in `parse_module'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1676:in `parse_statements'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1874:in `parse_top_level_statements'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:2000:in `block in scan'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1998:in `catch'
    from /usr/lib/ruby/2.3.0/rdoc/parser/ruby.rb:1998:in `scan'
    from /usr/lib/ruby/2.3.0/rdoc/rdoc.rb:375:in `parse_file'
    from /usr/lib/ruby/2.3.0/rdoc/rdoc.rb:426:in `block in parse_files'
    from /usr/lib/ruby/2.3.0/rdoc/rdoc.rb:424:in `map'
    from /usr/lib/ruby/2.3.0/rdoc/rdoc.rb:424:in `parse_files'
    from /usr/lib/ruby/2.3.0/rdoc/rubygems_hook.rb:197:in `block in generate'
    from /usr/lib/ruby/2.3.0/rdoc/rubygems_hook.rb:196:in `chdir'
    from /usr/lib/ruby/2.3.0/rdoc/rubygems_hook.rb:196:in `generate'
    from /usr/lib/ruby/2.3.0/rdoc/rubygems_hook.rb:57:in `block in generation_hook'
    from /usr/lib/ruby/2.3.0/rdoc/rubygems_hook.rb:56:in `each'
    from /usr/lib/ruby/2.3.0/rdoc/rubygems_hook.rb:56:in `generation_hook'
    from /usr/lib/ruby/site_ruby/2.3.0/rubygems/request_set.rb:189:in `block in install'
    from /usr/lib/ruby/site_ruby/2.3.0/rubygems/request_set.rb:188:in `each'
    from /usr/lib/ruby/site_ruby/2.3.0/rubygems/request_set.rb:188:in `install'
    from /usr/lib/ruby/site_ruby/2.3.0/rubygems/dependency_installer.rb:405:in `install'
    from /usr/lib/ruby/site_ruby/2.3.0/rubygems/commands/update_command.rb:213:in `update_gem'
    from /usr/lib/ruby/site_ruby/2.3.0/rubygems/commands/update_command.rb:225:in `block in update_gems'
    from /usr/lib/ruby/site_ruby/2.3.0/rubygems/commands/update_command.rb:224:in `each'
    from /usr/lib/ruby/site_ruby/2.3.0/rubygems/commands/update_command.rb:224:in `update_gems'
    from /usr/lib/ruby/site_ruby/2.3.0/rubygems/commands/update_command.rb:100:in `execute'
    from /usr/lib/ruby/site_ruby/2.3.0/rubygems/command.rb:310:in `invoke_with_build_args'
    from /usr/lib/ruby/site_ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'
    from /usr/lib/ruby/site_ruby/2.3.0/rubygems/command_manager.rb:139:in `run'
    from /usr/lib/ruby/site_ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'
```

I'd appreciate any help of yours in solving the issue.

Thanks!

**Comment by jneen** [comment]
It... looks like rdoc is running out of memory? Does it fail at the same place every time?

**Comment by aytekinar** [comment]
Yes. It has been like this since `v2.0.0` afaik. Please also check [this link][1]. Apparently I am not the only one. I could not find a solution tho, with 5 minutes of fast searching in DuckDuckGo.

[1]: https://aur.archlinux.org/packages/ruby-rouge/

**Comment by jneen** [comment]
That's really odd - rouge's documentation uses [yardoc](http://yardoc.org/), which afaict is pretty standard. `rake doc` compiles just fine, and the yardocs seem to be used on rubydoc.info: http://www.rubydoc.info/gems/rouge/2.0.2

I'm not sure what command the thing is running to generate docs...

**Comment by jneen** [comment]
Ooooookay so `rdoc .` *does* hang and also does a number of Very Wrong Things like scanning the `tmp/` directory and other files that aren't in the gemspec. Additionally, it misparses a number of regexes, and completely freezes when encountering strings of the form `%<...>`, which we were using for HTML in the HTMLTable and HTMLPygments formatters. Changing them to `%(...)` fixes the crash, but the deeper issue is how to get rubygems to not try to throw rdoc with its... incompletely implemented parsing at this project.

**Comment by segiddins** [comment]
As a temporary workaround, installing with --no-document should help

**Comment by aytekinar** [comment]
@jneen I don't know :( Unfortunately I am just a user --- I wish I had the knowledge to understand/help you. You're the master...

@segiddins I will try this for a while, thanks!

**Comment by jneen** [comment]
No worries, I thank you for the patience you've had so far! I've opened an issue open with RDoc: https://github.com/rdoc/rdoc/issues/410

**Comment by aycabta** [comment]
@jneen Thank you for your reporting at https://github.com/ruby/rdoc/issues/410, and I fixed it. Please check it from master branch or wait RDoc 6.0.0 what will be released some months later.
