### ISSUE TITLE
Consider Highlighting Support for exceptions and stacktraces

### ISSUE THREAD

**Issue by redrezo** [rouge-ruby/rouge#519]
in bug trackers you often need to post stacktraces
it would be nice to have for some languages stacktrace support to make them better readable

you could for example introduce an extra language named java-error or java-stacktrace to highlight those

for example:

``` java
Exception in thread "main" java.lang.NullPointerException
    at Printer.printString(Printer.java:13)
    at Printer.print(Printer.java:9)
    at Printer.main(Printer.java:19)
```

uses java highlighting.

while IDEs like eclipse highlight stacktraces like so:

![simplestacktrace](https://cloud.githubusercontent.com/assets/429967/17208478/394c1a7e-54b9-11e6-80b3-8ee5fd8626d1.png)

**Comment by ice1000** [comment]
I think this should be useful

**Comment by pyrmont** [comment]
@ice1000 At this stage in its development, Rouge predominantly relies on submissions from its community for new lexers. We certainly encourage new submissions, although I am sometimes a little slow to review them!

Documentation on writing a lexer is available [here](https://rouge-ruby.github.io/docs/file.LexerDevelopment.html).

**Comment by pyrmont** [comment]
I should just note that we've changed the policy for marking issues as stale from when this was originally closed last year. Issues tagged as `lexer-request` are now exempt. I've reopened this and tagged it appropriately.

**Comment by nbenitez** [comment]
Workaround note: For anyone looking to highlight GDB C stacktraces, the `csharp` highlighter works reasonably well (see example [here](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2448#note_1857726)).
